/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.esdras.gui;

import com.esdras.client.ClimateClient;
import com.esdras.climate.ClimateResponse;
import io.grpc.stub.StreamObserver;
import javax.swing.SwingUtilities;
/**
 *
 * @author EMoreira
 */
public class ClimatePanel extends javax.swing.JPanel {
    private ClimateClient climateClient;
    private boolean streaming = false;
    
    private ClimateResponse lastClimateResponse;
    private boolean liveClimateRunning = false;
    
    private AlertPanel alertPanel;

    /**
     * Creates new form ClimatePanel
     */
    public ClimatePanel() {
        initComponents();
        
        cbLocationActionPerformed(null);
        try {
            climateClient = new ClimateClient();
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Could not find ClimateSensorService.\nMake sure the server is running first.\n\n" + e.getMessage(),
                "Service Not Found",
                javax.swing.JOptionPane.ERROR_MESSAGE);
        }

        jTextField1.setEditable(false);
        jTextField2.setEditable(false);
        jTextField3.setEditable(false);
        jTextField4.setEditable(false);
        jTextField5.setEditable(false);
        
        jButton3.setVisible(false);
        
        setBorder(javax.swing.BorderFactory.createTitledBorder(
            javax.swing.BorderFactory.createEtchedBorder(),
            "CLIMATE DATA",
            javax.swing.border.TitledBorder.CENTER,
            javax.swing.border.TitledBorder.TOP
        ));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        cbStation = new javax.swing.JComboBox<>();
        cbLocation = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();

        jLabel2.setText("Location:");

        jLabel3.setText("Station:");

        jButton1.setBackground(new java.awt.Color(102, 204, 255));
        jButton1.setLabel("Get Current Data");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(102, 255, 0));
        jButton2.setText("Start Live Monitoring");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(255, 51, 0));
        jButton3.setLabel("Stop Stream");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        cbStation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbLocation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dublin", "Bray" }));
        cbLocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbLocationActionPerformed(evt);
            }
        });

        jLabel4.setText("Temperature:");

        jLabel5.setText("Humidity:");

        jLabel6.setText("Pressure:");

        jLabel7.setText("WindSpeed:");

        jLabel8.setText("Time:");

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(50, 50, 50)
                                .addComponent(jTextField5))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(cbLocation, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbStation, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel5))
                                        .addGap(9, 9, 9)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                                            .addComponent(jTextField2))
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel7))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(243, 243, 243)
                                        .addComponent(jLabel6)))
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField3, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                                    .addComponent(jTextField4)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbStation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addContainerGap(41, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
               String location = cbLocation.getSelectedItem().toString();
               String stationId = cbStation.getSelectedItem().toString();

               ClimateResponse response = climateClient.getCurrentClimateData(location, stationId);

               updateClimateFields(response);
               
                if (alertPanel != null) {
                    alertPanel.enableStormAlertButton();
                }

           } catch (Exception e) {
               javax.swing.JOptionPane.showMessageDialog(this,
                       "Error connecting to Climate Service:\n" + e.getMessage(),
                       "Connection Error",
                       javax.swing.JOptionPane.ERROR_MESSAGE);
           }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void cbLocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbLocationActionPerformed
        // TODO add your handling code here:
        String cidadeSelecionada = cbLocation.getSelectedItem().toString();

        // 2. Limpa todas as opções que estavam no segundo combobox
        cbStation.removeAllItems();

        // 3. Adiciona as novas opções dependendo da cidade escolhida
        if (cidadeSelecionada.equals("Dublin")) {
            cbStation.addItem("DUB-ST01");
            cbStation.addItem("DUB-ST02");
        } else if (cidadeSelecionada.equals("Bray")) {
            cbStation.addItem("BRY-ST01");
        }else {
            cbStation.addItem("Select the city first...");
        }
    }//GEN-LAST:event_cbLocationActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here
        if (streaming) {
            return;
        }

        streaming = true;
        
        liveClimateRunning = true;

        jButton2.setEnabled(false);
        jButton3.setVisible(true);
        jButton1.setEnabled(false);

        String location = cbLocation.getSelectedItem().toString();
        String stationId = cbStation.getSelectedItem().toString();

        climateClient.streamLiveClimateData(location, stationId, new StreamObserver<ClimateResponse>() {

            @Override
            public void onNext(ClimateResponse response) {
                SwingUtilities.invokeLater(() -> {
                    updateClimateFields(response);
                });
            }

            @Override
            public void onError(Throwable t) {
                streaming = false;
                liveClimateRunning = false;

                boolean wasCancelledByUser = t instanceof io.grpc.StatusRuntimeException
                            && ((io.grpc.StatusRuntimeException) t).getStatus().getCode()
                               == io.grpc.Status.Code.CANCELLED;

                SwingUtilities.invokeLater(() -> {
                    jButton2.setEnabled(true);
                    jButton3.setVisible(false);
                    jButton1.setEnabled(true);
                    if (!wasCancelledByUser) {
                        javax.swing.JOptionPane.showMessageDialog(ClimatePanel.this,
                                "Streaming error:\n" + t.getMessage(),
                                "Stream Error",
                                javax.swing.JOptionPane.ERROR_MESSAGE);
                    }
                });  
            }

            @Override
            public void onCompleted() {
                streaming = false;
                liveClimateRunning = false;

                SwingUtilities.invokeLater(() -> {
                    jButton2.setEnabled(true);
                    jButton3.setVisible(false);
                    jButton1.setEnabled(true);
                });
            }
        });
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here: 
        climateClient.cancelStream(); // stopping the while loop cleanly.
        liveClimateRunning = false; // alerts no running
        streaming = false;
        jButton2.setEnabled(true);
        jButton3.setVisible(false);
        jButton1.setEnabled(true);
        if(alertPanel != null){
            alertPanel.stopLiveAlertFeed();  
        }
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void updateClimateFields(ClimateResponse response) {
        lastClimateResponse = response;
        jTextField1.setText(String.format("%.2f °C", response.getTemperature()));
        jTextField2.setText(String.format("%.2f %%", response.getHumidity()));
        jTextField3.setText(String.format("%.2f hPa", response.getPressure()));
        jTextField4.setText(String.format("%.2f km/h", response.getWindSpeed()));
        jTextField5.setText(response.getTimestamp());
    }
    
    public ClimateResponse getLastClimateResponse() {
        return lastClimateResponse;
    }
    
    public boolean isLiveClimateRunning() {
        return liveClimateRunning;
    }

    public String getSelectedLocation() {
        return cbLocation.getSelectedItem().toString();
    }
    
    public void setAlertPanel(AlertPanel alertPanel) {
        this.alertPanel = alertPanel;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbLocation;
    private javax.swing.JComboBox<String> cbStation;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
