/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.esdras.gui;

import com.esdras.client.RiverClient;
import com.esdras.river.RiverResponse;
import io.grpc.stub.StreamObserver;
/**
 *
 * @author EMoreira
 */
public class RiverPanel extends javax.swing.JPanel {

    /**
     * Creates new form RiverPanel
     */
    
    private RiverClient riverClient;
    private boolean liveRiverRunning = false;
    private double riverLevel = 0.0;
    private AlertPanel alertPanel;
        
    public RiverPanel() {
        initComponents();
        ButtonStopLive.setVisible(false);
        riverClient = new RiverClient();
        
        riverLevelOutput.setEditable(false);
        timestampOutput.setEditable(false);
        floodRiskOutput.setEditable(false);
        avgRainOutput.setEditable(false);
        
        setBorder(javax.swing.BorderFactory.createTitledBorder(
            javax.swing.BorderFactory.createEtchedBorder(),
            "RIVER MONITORING",
            javax.swing.border.TitledBorder.CENTER,
            javax.swing.border.TitledBorder.TOP
        ));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        CBRiverLocation = new javax.swing.JComboBox<>();
        ButtonGetRiverLevel = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        riverLevelOutput = new javax.swing.JTextField();
        timestampOutput = new javax.swing.JTextField();
        floodRiskOutput = new javax.swing.JTextField();
        avgRainOutput = new javax.swing.JTextField();
        ButtonCheckRiskAndAvgRain = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        ButtonStartLiveMonitoring = new javax.swing.JToggleButton();
        jLabel8 = new javax.swing.JLabel();
        numberOfDaysField = new javax.swing.JSpinner();
        ButtonStopLive = new javax.swing.JToggleButton();

        jLabel2.setText("River/Location:");

        CBRiverLocation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lifey - Dublin", "Lee - Cork" }));

        ButtonGetRiverLevel.setBackground(new java.awt.Color(102, 204, 255));
        ButtonGetRiverLevel.setText("Get River Level");
        ButtonGetRiverLevel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonGetRiverLevelActionPerformed(evt);
            }
        });

        jLabel3.setText("River Level:");

        jLabel4.setText("avg ");

        jLabel5.setText("Flood Risk:");

        jLabel6.setText("Timestamp:");

        riverLevelOutput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                riverLevelOutputActionPerformed(evt);
            }
        });

        timestampOutput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timestampOutputActionPerformed(evt);
            }
        });

        floodRiskOutput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                floodRiskOutputActionPerformed(evt);
            }
        });

        avgRainOutput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                avgRainOutputActionPerformed(evt);
            }
        });

        ButtonCheckRiskAndAvgRain.setBackground(new java.awt.Color(102, 204, 255));
        ButtonCheckRiskAndAvgRain.setText("Check risk and avg");
        ButtonCheckRiskAndAvgRain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCheckRiskAndAvgRainActionPerformed(evt);
            }
        });

        jLabel7.setText("Rainy Days: ");

        ButtonStartLiveMonitoring.setBackground(new java.awt.Color(102, 255, 0));
        ButtonStartLiveMonitoring.setText("Start Live Monitoring");
        ButtonStartLiveMonitoring.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonStartLiveMonitoringActionPerformed(evt);
            }
        });

        numberOfDaysField.setValue(1);

        ButtonStopLive.setBackground(new java.awt.Color(255, 0, 0));
        ButtonStopLive.setText("Stop Live Monitoring");
        ButtonStopLive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonStopLiveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(CBRiverLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ButtonStartLiveMonitoring)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ButtonGetRiverLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(riverLevelOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(timestampOutput)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(2, 2, 2)
                            .addComponent(numberOfDaysField)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(ButtonCheckRiskAndAvgRain)
                            .addGap(78, 78, 78))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addGap(233, 233, 233)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(floodRiskOutput)
                            .addComponent(avgRainOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(106, 106, 106))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(ButtonStopLive)
                .addGap(301, 301, 301))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel7))
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CBRiverLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonGetRiverLevel)
                    .addComponent(ButtonCheckRiskAndAvgRain)
                    .addComponent(numberOfDaysField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonStartLiveMonitoring)
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(riverLevelOutput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(floodRiskOutput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel4)
                    .addComponent(timestampOutput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(avgRainOutput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(ButtonStopLive)
                .addGap(26, 26, 26)
                .addComponent(jLabel8)
                .addGap(0, 88, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonGetRiverLevelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonGetRiverLevelActionPerformed
        // TODO add your handling code here:
        try {
               String location = CBRiverLocation.getSelectedItem().toString();

               RiverResponse response = riverClient.getCurrentRiverLevel(location);

                riverLevelOutput.setText(String.format("%.2f level", response.getRiverLevel()));
                floodRiskOutput.setText(response.getRiskStatus());
                timestampOutput.setText(response.getTimestamp());
                avgRainOutput.setText("");

           } catch (Exception e) {
               javax.swing.JOptionPane.showMessageDialog(this,
                       "Error connecting:\n" + e.getMessage(),
                       "Connection Error",
                       javax.swing.JOptionPane.ERROR_MESSAGE);
           }
    }//GEN-LAST:event_ButtonGetRiverLevelActionPerformed

    private void timestampOutputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timestampOutputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_timestampOutputActionPerformed

    private void riverLevelOutputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_riverLevelOutputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_riverLevelOutputActionPerformed

    private void floodRiskOutputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_floodRiskOutputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_floodRiskOutputActionPerformed

    private void avgRainOutputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_avgRainOutputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_avgRainOutputActionPerformed

    private void ButtonCheckRiskAndAvgRainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCheckRiskAndAvgRainActionPerformed
        // TODO add your handling code here:
        String location = CBRiverLocation.getSelectedItem().toString();
        int days;

        try {
            days = (Integer) numberOfDaysField.getValue();
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Enter a valid number of rainy days.");
            return;
        }

        riverClient.uploadRainfallData(location, days, new io.grpc.stub.StreamObserver<com.esdras.river.RainfallAnalysis>() {
            @Override
            public void onNext(com.esdras.river.RainfallAnalysis analysis) {
                javax.swing.SwingUtilities.invokeLater(() -> {
                    avgRainOutput.setText(String.format("%.2f mm", analysis.getAverageRainfall()));
                    floodRiskOutput.setText(analysis.getFloodRiskIndicator());
                });
            }

            @Override
            public void onError(Throwable t) {
                System.out.println(t);
                javax.swing.SwingUtilities.invokeLater(() -> {
                    javax.swing.JOptionPane.showMessageDialog(RiverPanel.this,
                            "Error receiving rainfall analysis: " + t.getMessage());
                });
            }

            @Override
            public void onCompleted() {
                System.out.println("Rainfall analysis completed.");
            }
        });
    }//GEN-LAST:event_ButtonCheckRiskAndAvgRainActionPerformed

    private void ButtonStartLiveMonitoringActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonStartLiveMonitoringActionPerformed
        // TODO add your handling code here:
        ButtonStartLiveMonitoring.setEnabled(false);
        ButtonCheckRiskAndAvgRain.setEnabled(false);
        ButtonGetRiverLevel.setEnabled(false);
        ButtonStopLive.setVisible(true);
        String location = (String) CBRiverLocation.getSelectedItem();
        liveRiverRunning = true;

        StreamObserver<RiverResponse> responseObserver = new StreamObserver<RiverResponse>() {
            @Override
            public void onNext(RiverResponse response) {
                javax.swing.SwingUtilities.invokeLater(() -> {
                    riverLevelOutput.setText(String.format("%.2f metres", response.getRiverLevel()));
                    floodRiskOutput.setText(response.getRiskStatus());
                    timestampOutput.setText(response.getTimestamp());
                    riverLevel = response.getRiverLevel();
                });
            }

            @Override
            public void onError(Throwable t) {
                liveRiverRunning = false;
                System.out.println("Error: " + t.getMessage());
                javax.swing.JOptionPane.showMessageDialog(RiverPanel.this,
                        "Streaming error:\n" + t.getMessage(),
                        "Stream Error",
                        javax.swing.JOptionPane.ERROR_MESSAGE); 
            }

            @Override
            public void onCompleted() {
                liveRiverRunning = false;
                System.out.println("Live monitoring finished.");
            }
        };

        riverClient.startLiveMonitoring(location, responseObserver);
    }//GEN-LAST:event_ButtonStartLiveMonitoringActionPerformed

    private void ButtonStopLiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonStopLiveActionPerformed
        // TODO add your handling code here:
        ButtonStartLiveMonitoring.setEnabled(true); 
        ButtonCheckRiskAndAvgRain.setEnabled(true);
        ButtonGetRiverLevel.setEnabled(true);
        ButtonStopLive.setVisible(false);
        riverClient.stopLiveMonitoring();
        liveRiverRunning = false;
        if(alertPanel != null){
            alertPanel.stopLiveAlertFeed();  
        }
    }//GEN-LAST:event_ButtonStopLiveActionPerformed

    public boolean isLiveRiverRunning() {
        return liveRiverRunning;
    }
    
    public double getRiverLevel() {
        return riverLevel;
    }
    
    public void setAlertPanel(AlertPanel alertPanel) {
        this.alertPanel = alertPanel;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonCheckRiskAndAvgRain;
    private javax.swing.JButton ButtonGetRiverLevel;
    private javax.swing.JToggleButton ButtonStartLiveMonitoring;
    private javax.swing.JToggleButton ButtonStopLive;
    private javax.swing.JComboBox<String> CBRiverLocation;
    private javax.swing.JTextField avgRainOutput;
    private javax.swing.JTextField floodRiskOutput;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSpinner numberOfDaysField;
    private javax.swing.JTextField riverLevelOutput;
    private javax.swing.JTextField timestampOutput;
    // End of variables declaration//GEN-END:variables
}
