// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RiverLevelProto.proto

package com.esdras.river;

public interface RainfallAnalysisOrBuilder extends
    // @@protoc_insertion_point(interface_extends:river.RainfallAnalysis)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double averageRainfall = 1;</code>
   */
  double getAverageRainfall();

  /**
   * <code>string floodRiskIndicator = 2;</code>
   */
  java.lang.String getFloodRiskIndicator();
  /**
   * <code>string floodRiskIndicator = 2;</code>
   */
  com.google.protobuf.ByteString
      getFloodRiskIndicatorBytes();
}
