// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RiverLevelProto.proto

package com.esdras.river;

/**
 * Protobuf type {@code river.RainfallAnalysis}
 */
public  final class RainfallAnalysis extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:river.RainfallAnalysis)
    RainfallAnalysisOrBuilder {
private static final long serialVersionUID = 0L;
  // Use RainfallAnalysis.newBuilder() to construct.
  private RainfallAnalysis(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private RainfallAnalysis() {
    averageRainfall_ = 0D;
    floodRiskIndicator_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private RainfallAnalysis(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 9: {

            averageRainfall_ = input.readDouble();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            floodRiskIndicator_ = s;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.esdras.river.RiverLevelProto.internal_static_river_RainfallAnalysis_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.esdras.river.RiverLevelProto.internal_static_river_RainfallAnalysis_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.esdras.river.RainfallAnalysis.class, com.esdras.river.RainfallAnalysis.Builder.class);
  }

  public static final int AVERAGERAINFALL_FIELD_NUMBER = 1;
  private double averageRainfall_;
  /**
   * <code>double averageRainfall = 1;</code>
   */
  public double getAverageRainfall() {
    return averageRainfall_;
  }

  public static final int FLOODRISKINDICATOR_FIELD_NUMBER = 2;
  private volatile java.lang.Object floodRiskIndicator_;
  /**
   * <code>string floodRiskIndicator = 2;</code>
   */
  public java.lang.String getFloodRiskIndicator() {
    java.lang.Object ref = floodRiskIndicator_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      floodRiskIndicator_ = s;
      return s;
    }
  }
  /**
   * <code>string floodRiskIndicator = 2;</code>
   */
  public com.google.protobuf.ByteString
      getFloodRiskIndicatorBytes() {
    java.lang.Object ref = floodRiskIndicator_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      floodRiskIndicator_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (averageRainfall_ != 0D) {
      output.writeDouble(1, averageRainfall_);
    }
    if (!getFloodRiskIndicatorBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, floodRiskIndicator_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (averageRainfall_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(1, averageRainfall_);
    }
    if (!getFloodRiskIndicatorBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, floodRiskIndicator_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.esdras.river.RainfallAnalysis)) {
      return super.equals(obj);
    }
    com.esdras.river.RainfallAnalysis other = (com.esdras.river.RainfallAnalysis) obj;

    boolean result = true;
    result = result && (
        java.lang.Double.doubleToLongBits(getAverageRainfall())
        == java.lang.Double.doubleToLongBits(
            other.getAverageRainfall()));
    result = result && getFloodRiskIndicator()
        .equals(other.getFloodRiskIndicator());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + AVERAGERAINFALL_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getAverageRainfall()));
    hash = (37 * hash) + FLOODRISKINDICATOR_FIELD_NUMBER;
    hash = (53 * hash) + getFloodRiskIndicator().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.esdras.river.RainfallAnalysis parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.esdras.river.RainfallAnalysis parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.esdras.river.RainfallAnalysis parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.esdras.river.RainfallAnalysis parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.esdras.river.RainfallAnalysis parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.esdras.river.RainfallAnalysis parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.esdras.river.RainfallAnalysis parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.esdras.river.RainfallAnalysis parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.esdras.river.RainfallAnalysis parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.esdras.river.RainfallAnalysis parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.esdras.river.RainfallAnalysis parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.esdras.river.RainfallAnalysis parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.esdras.river.RainfallAnalysis prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code river.RainfallAnalysis}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:river.RainfallAnalysis)
      com.esdras.river.RainfallAnalysisOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.esdras.river.RiverLevelProto.internal_static_river_RainfallAnalysis_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.esdras.river.RiverLevelProto.internal_static_river_RainfallAnalysis_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.esdras.river.RainfallAnalysis.class, com.esdras.river.RainfallAnalysis.Builder.class);
    }

    // Construct using com.esdras.river.RainfallAnalysis.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      averageRainfall_ = 0D;

      floodRiskIndicator_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.esdras.river.RiverLevelProto.internal_static_river_RainfallAnalysis_descriptor;
    }

    @java.lang.Override
    public com.esdras.river.RainfallAnalysis getDefaultInstanceForType() {
      return com.esdras.river.RainfallAnalysis.getDefaultInstance();
    }

    @java.lang.Override
    public com.esdras.river.RainfallAnalysis build() {
      com.esdras.river.RainfallAnalysis result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.esdras.river.RainfallAnalysis buildPartial() {
      com.esdras.river.RainfallAnalysis result = new com.esdras.river.RainfallAnalysis(this);
      result.averageRainfall_ = averageRainfall_;
      result.floodRiskIndicator_ = floodRiskIndicator_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.esdras.river.RainfallAnalysis) {
        return mergeFrom((com.esdras.river.RainfallAnalysis)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.esdras.river.RainfallAnalysis other) {
      if (other == com.esdras.river.RainfallAnalysis.getDefaultInstance()) return this;
      if (other.getAverageRainfall() != 0D) {
        setAverageRainfall(other.getAverageRainfall());
      }
      if (!other.getFloodRiskIndicator().isEmpty()) {
        floodRiskIndicator_ = other.floodRiskIndicator_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.esdras.river.RainfallAnalysis parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.esdras.river.RainfallAnalysis) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private double averageRainfall_ ;
    /**
     * <code>double averageRainfall = 1;</code>
     */
    public double getAverageRainfall() {
      return averageRainfall_;
    }
    /**
     * <code>double averageRainfall = 1;</code>
     */
    public Builder setAverageRainfall(double value) {
      
      averageRainfall_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double averageRainfall = 1;</code>
     */
    public Builder clearAverageRainfall() {
      
      averageRainfall_ = 0D;
      onChanged();
      return this;
    }

    private java.lang.Object floodRiskIndicator_ = "";
    /**
     * <code>string floodRiskIndicator = 2;</code>
     */
    public java.lang.String getFloodRiskIndicator() {
      java.lang.Object ref = floodRiskIndicator_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        floodRiskIndicator_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string floodRiskIndicator = 2;</code>
     */
    public com.google.protobuf.ByteString
        getFloodRiskIndicatorBytes() {
      java.lang.Object ref = floodRiskIndicator_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        floodRiskIndicator_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string floodRiskIndicator = 2;</code>
     */
    public Builder setFloodRiskIndicator(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      floodRiskIndicator_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string floodRiskIndicator = 2;</code>
     */
    public Builder clearFloodRiskIndicator() {
      
      floodRiskIndicator_ = getDefaultInstance().getFloodRiskIndicator();
      onChanged();
      return this;
    }
    /**
     * <code>string floodRiskIndicator = 2;</code>
     */
    public Builder setFloodRiskIndicatorBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      floodRiskIndicator_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:river.RainfallAnalysis)
  }

  // @@protoc_insertion_point(class_scope:river.RainfallAnalysis)
  private static final com.esdras.river.RainfallAnalysis DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.esdras.river.RainfallAnalysis();
  }

  public static com.esdras.river.RainfallAnalysis getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RainfallAnalysis>
      PARSER = new com.google.protobuf.AbstractParser<RainfallAnalysis>() {
    @java.lang.Override
    public RainfallAnalysis parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new RainfallAnalysis(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<RainfallAnalysis> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RainfallAnalysis> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.esdras.river.RainfallAnalysis getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

