// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RiverLevelProto.proto

package com.esdras.river;

public interface RainfallDataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:river.RainfallData)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string location = 1;</code>
   */
  java.lang.String getLocation();
  /**
   * <code>string location = 1;</code>
   */
  com.google.protobuf.ByteString
      getLocationBytes();

  /**
   * <code>double rainfallAmount = 2;</code>
   */
  double getRainfallAmount();

  /**
   * <code>string timestamp = 3;</code>
   */
  java.lang.String getTimestamp();
  /**
   * <code>string timestamp = 3;</code>
   */
  com.google.protobuf.ByteString
      getTimestampBytes();
}
