// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RiverLevelProto.proto

package com.esdras.river;

public interface RiverResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:river.RiverResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double riverLevel = 1;</code>
   */
  double getRiverLevel();

  /**
   * <code>string riskStatus = 2;</code>
   */
  java.lang.String getRiskStatus();
  /**
   * <code>string riskStatus = 2;</code>
   */
  com.google.protobuf.ByteString
      getRiskStatusBytes();

  /**
   * <code>string timestamp = 3;</code>
   */
  java.lang.String getTimestamp();
  /**
   * <code>string timestamp = 3;</code>
   */
  com.google.protobuf.ByteString
      getTimestampBytes();
}
