// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RiverLevelProto.proto

package com.esdras.river;

public interface RiverRequestBidiOrBuilder extends
    // @@protoc_insertion_point(interface_extends:river.RiverRequestBidi)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string location = 1;</code>
   */
  java.lang.String getLocation();
  /**
   * <code>string location = 1;</code>
   */
  com.google.protobuf.ByteString
      getLocationBytes();

  /**
   * <code>double riverLevel = 2;</code>
   */
  double getRiverLevel();
}
