// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RiverLevelProto.proto

package com.esdras.river;

public final class RiverLevelProto {
  private RiverLevelProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_river_RiverRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_river_RiverRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_river_RiverResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_river_RiverResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_river_RainfallData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_river_RainfallData_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_river_RainfallAnalysis_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_river_RainfallAnalysis_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_river_RiverRequestBidi_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_river_RiverRequestBidi_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025RiverLevelProto.proto\022\005river\" \n\014RiverR" +
      "equest\022\020\n\010location\030\001 \001(\t\"J\n\rRiverRespons" +
      "e\022\022\n\nriverLevel\030\001 \001(\001\022\022\n\nriskStatus\030\002 \001(" +
      "\t\022\021\n\ttimestamp\030\003 \001(\t\"8\n\014RainfallData\022\020\n\010" +
      "location\030\001 \001(\t\022\026\n\016rainfallAmount\030\002 \001(\001\"G" +
      "\n\020RainfallAnalysis\022\027\n\017averageRainfall\030\001 " +
      "\001(\001\022\032\n\022floodRiskIndicator\030\002 \001(\t\"8\n\020River" +
      "RequestBidi\022\020\n\010location\030\001 \001(\t\022\022\n\nriverLe" +
      "vel\030\002 \001(\0012\350\001\n\021RiverLevelService\022A\n\024getCu" +
      "rrentRiverLevel\022\023.river.RiverRequest\032\024.r" +
      "iver.RiverResponse\022D\n\022uploadRainfallData" +
      "\022\023.river.RainfallData\032\027.river.RainfallAn" +
      "alysis(\001\022J\n\025monitorRiverLevelLive\022\027.rive" +
      "r.RiverRequestBidi\032\024.river.RiverResponse" +
      "(\0010\001B%\n\020com.esdras.riverB\017RiverLevelProt" +
      "oP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_river_RiverRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_river_RiverRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_river_RiverRequest_descriptor,
        new java.lang.String[] { "Location", });
    internal_static_river_RiverResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_river_RiverResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_river_RiverResponse_descriptor,
        new java.lang.String[] { "RiverLevel", "RiskStatus", "Timestamp", });
    internal_static_river_RainfallData_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_river_RainfallData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_river_RainfallData_descriptor,
        new java.lang.String[] { "Location", "RainfallAmount", });
    internal_static_river_RainfallAnalysis_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_river_RainfallAnalysis_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_river_RainfallAnalysis_descriptor,
        new java.lang.String[] { "AverageRainfall", "FloodRiskIndicator", });
    internal_static_river_RiverRequestBidi_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_river_RiverRequestBidi_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_river_RiverRequestBidi_descriptor,
        new java.lang.String[] { "Location", "RiverLevel", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
