// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DisasterAlertProto.proto

package com.esdras.alert;

public interface AlertRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:alert.AlertRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string location = 1;</code>
   */
  java.lang.String getLocation();
  /**
   * <code>string location = 1;</code>
   */
  com.google.protobuf.ByteString
      getLocationBytes();

  /**
   * <code>double temperature = 2;</code>
   */
  double getTemperature();

  /**
   * <code>double humidity = 3;</code>
   */
  double getHumidity();

  /**
   * <code>double windSpeed = 4;</code>
   */
  double getWindSpeed();

  /**
   * <code>double pressure = 5;</code>
   */
  double getPressure();

  /**
   * <code>string timestamp = 6;</code>
   */
  java.lang.String getTimestamp();
  /**
   * <code>string timestamp = 6;</code>
   */
  com.google.protobuf.ByteString
      getTimestampBytes();
}
