// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DisasterAlertProto.proto

package com.esdras.alert;

public interface AlertResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:alert.AlertResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string alertType = 1;</code>
   */
  java.lang.String getAlertType();
  /**
   * <code>string alertType = 1;</code>
   */
  com.google.protobuf.ByteString
      getAlertTypeBytes();

  /**
   * <code>string severityLevel = 2;</code>
   */
  java.lang.String getSeverityLevel();
  /**
   * <code>string severityLevel = 2;</code>
   */
  com.google.protobuf.ByteString
      getSeverityLevelBytes();

  /**
   * <code>string message = 3;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 3;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <code>string timestamp = 4;</code>
   */
  java.lang.String getTimestamp();
  /**
   * <code>string timestamp = 4;</code>
   */
  com.google.protobuf.ByteString
      getTimestampBytes();
}
