// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DisasterAlertProto.proto

package com.esdras.alert;

public interface AlertStreamRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:alert.AlertStreamRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string location = 1;</code>
   */
  java.lang.String getLocation();
  /**
   * <code>string location = 1;</code>
   */
  com.google.protobuf.ByteString
      getLocationBytes();
}
