// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DisasterAlertProto.proto

package com.esdras.alert;

public interface LiveAlertRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:alert.LiveAlertRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * climate live
   * </pre>
   *
   * <code>double temperature = 1;</code>
   */
  double getTemperature();

  /**
   * <code>double humidity = 2;</code>
   */
  double getHumidity();

  /**
   * <code>double windSpeed = 3;</code>
   */
  double getWindSpeed();

  /**
   * <code>double pressure = 4;</code>
   */
  double getPressure();

  /**
   * <pre>
   * river live
   * </pre>
   *
   * <code>double riverLevel = 5;</code>
   */
  double getRiverLevel();

  /**
   * <code>string timestamp = 6;</code>
   */
  java.lang.String getTimestamp();
  /**
   * <code>string timestamp = 6;</code>
   */
  com.google.protobuf.ByteString
      getTimestampBytes();
}
