// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ClimateSensorProto.proto

package com.esdras.climate;

public interface ClimateRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:climate.ClimateRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string location = 1;</code>
   */
  java.lang.String getLocation();
  /**
   * <code>string location = 1;</code>
   */
  com.google.protobuf.ByteString
      getLocationBytes();

  /**
   * <code>string stationId = 2;</code>
   */
  java.lang.String getStationId();
  /**
   * <code>string stationId = 2;</code>
   */
  com.google.protobuf.ByteString
      getStationIdBytes();
}
