// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ClimateSensorProto.proto

package com.esdras.climate;

public final class ClimateSensorProto {
  private ClimateSensorProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_climate_ClimateRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_climate_ClimateRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_climate_ClimateResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_climate_ClimateResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030ClimateSensorProto.proto\022\007climate\"5\n\016C" +
      "limateRequest\022\020\n\010location\030\001 \001(\t\022\021\n\tstati" +
      "onId\030\002 \001(\t\"p\n\017ClimateResponse\022\023\n\013tempera" +
      "ture\030\001 \001(\001\022\020\n\010humidity\030\002 \001(\001\022\020\n\010pressure" +
      "\030\003 \001(\001\022\021\n\twindSpeed\030\004 \001(\001\022\021\n\ttimestamp\030\005" +
      " \001(\t2\260\001\n\024ClimateSensorService\022J\n\025getCurr" +
      "entClimateData\022\027.climate.ClimateRequest\032" +
      "\030.climate.ClimateResponse\022L\n\025streamLiveC" +
      "limateData\022\027.climate.ClimateRequest\032\030.cl" +
      "imate.ClimateResponse0\001B*\n\022com.esdras.cl" +
      "imateB\022ClimateSensorProtoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_climate_ClimateRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_climate_ClimateRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_climate_ClimateRequest_descriptor,
        new java.lang.String[] { "Location", "StationId", });
    internal_static_climate_ClimateResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_climate_ClimateResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_climate_ClimateResponse_descriptor,
        new java.lang.String[] { "Temperature", "Humidity", "Pressure", "WindSpeed", "Timestamp", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
