// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ClimateSensorProto.proto

package com.esdras.climate;

public interface ClimateResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:climate.ClimateResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double temperature = 1;</code>
   */
  double getTemperature();

  /**
   * <code>double humidity = 2;</code>
   */
  double getHumidity();

  /**
   * <code>double pressure = 3;</code>
   */
  double getPressure();

  /**
   * <code>double windSpeed = 4;</code>
   */
  double getWindSpeed();

  /**
   * <code>string timestamp = 5;</code>
   */
  java.lang.String getTimestamp();
  /**
   * <code>string timestamp = 5;</code>
   */
  com.google.protobuf.ByteString
      getTimestampBytes();
}
